### ISSUE TITLE
new Advertisement class - KeyError: 'ads_shippable' when trying to use shippable_ads()

### ISSUE THREAD

**Issue by brunetton** [Shinyhero36/Leboncoin-API-Wrapper#12]
```python
from leboncoin_api_wrapper import Leboncoin

lbc = Leboncoin()
lbc.searchFor("Kindle Paperwhite 3")
results = lbc.execute()
results.shippable_ads()
```

=> KeyError: 'ads_shippable'

I don't see any `shippable_ads` in API result

## Start of fix

I implemented yesterday a little function to determine if an ad is shippable:

```python
def is_shippeable(ad):
    shippable_attr = [e for e in ad['attributes'] if e['key'] == 'shippable']
    return shippable_attr != [] and shippable_attr[0]['value'] == 'true'
```

And in action with an example:
```python
from leboncoin_api_wrapper import Leboncoin

def is_shippeable(ad):
    shippable_attr = [e for e in ad['attributes'] if e['key'] == 'shippable']
    return shippable_attr != [] and shippable_attr[0]['value'] == 'true'

lbc = Leboncoin()
lbc.searchFor("Kindle Paperwhite 3")
results = lbc.execute()
for ad in results._['ads']:
    print(is_shippeable(ad), ad['url'])
```

PS: I do not use Advertisement class here (for now)

**Comment by Shinyhero36** [comment]
Can you please provide the full traceback for this

```python
from leboncoin_api_wrapper import Leboncoin

lbc = Leboncoin()
lbc.searchFor("Kindle Paperwhite 3")
results = lbc.execute()
results.shippable_ads()
```

Mine is this 
```text
Traceback (most recent call last):
  File "C:/Users/geral/Desktop/PycharmProjects/Leboncoin-API-Wrapper/examples/shippable_ads.py", line 9, in <module>
    results.shippable_ads()
  File "C:\Users\geral\Desktop\PycharmProjects\Leboncoin-API-Wrapper\leboncoin_api_wrapper\leboncoin.py", line 56, in shippable_ads
    return [Advertisement(**ad) for ad in self._["ads_shippable"]]
KeyError: 'ads_shippable'
```

because from the response I got [here](http://pastebin.fr/73029),
there is not key named **ads_shippable**

**Comment by Shinyhero36** [comment]
Found something new when you do this

```python
from leboncoin_api_wrapper import Leboncoin

lbc = Leboncoin()
lbc.searchFor("écran pc")
results = lbc.execute()

results.pprint()
```

In the json response [here](http://pastebin.fr/73031), there is no key named ads_shippable but there is **ads_alu** key and the **expiration_date** key within it

Related to #11

**Comment by brunetton** [comment]
> Can you please provide the full traceback for this
> 
> ```python
> from leboncoin_api_wrapper import Leboncoin
> 
> lbc = Leboncoin()
> lbc.searchFor("Kindle Paperwhite 3")
> results = lbc.execute()
> results.shippable_ads()
> ```
> 
> Mine is this
> 
> ```
> Traceback (most recent call last):
>   File "C:/Users/geral/Desktop/PycharmProjects/Leboncoin-API-Wrapper/examples/shippable_ads.py", line 9, in <module>
>     results.shippable_ads()
>   File "C:\Users\geral\Desktop\PycharmProjects\Leboncoin-API-Wrapper\leboncoin_api_wrapper\leboncoin.py", line 56, in shippable_ads
>     return [Advertisement(**ad) for ad in self._["ads_shippable"]]
> KeyError: 'ads_shippable'
> ```
> 
> because from the response I got [here](http://pastebin.fr/73029),
> there is not key named **ads_shippable**

Exactly the same problem here, in fact I don't think I ever got an `ads_shippable` key from API.
This has been introduced in https://github.com/Shinyhero36/Leboncoin-API-Wrapper/commit/8a9b88e7948e6253593064d1914f3789db569511, more preciesly on [this line](https://github.com/Shinyhero36/Leboncoin-API-Wrapper/commit/8a9b88e7948e6253593064d1914f3789db569511?branch=8a9b88e7948e6253593064d1914f3789db569511&diff=unified#diff-9c6138e438a90e9e60b773ea7b03419fcce3f0665234a3aaab3e543453b62cedR56)

**Comment by brunetton** [comment]
I propose to make a PR that replace this buggy `shippable_ads()` by the technique I used in my [first comment](https://github.com/Shinyhero36/Leboncoin-API-Wrapper/issues/12#issue-742814504) of this ticket
