### ISSUE TITLE
API HTTP error 403

### ISSUE THREAD

**Issue by dbecad** [Shinyhero36/Leboncoin-API-Wrapper#21]
Good day,
I was trying to check your current wrapper to implement a better sorting feature that they have on their website.
Currently I get a 403 for any request I'm executing, would you have a debug strategy to recommend?  
Note that I'm running from the US, so could they have localization restrictions?
Thanks
Cheers

```
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    results = lbc.execute()
  File "***/Leboncoin-API-Wrapper/leboncoin_api_wrapper/leboncoin.py", line 113, in execute
    r.raise_for_status()
  File "***/.local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.leboncoin.fr/finder/search
```

**Comment by Shinyhero36** [comment]
Hi,
Someone already had this issue #18, even though he wasn't in the US
It's possible the exception raised du to your location

The only thing I can recommand you is to wait a bit and see if the exception raises again

Cheers

**Comment by dbecad** [comment]
Ah, missed that issue when I looked the closed ones.
Thanks, will report if it gets better in the next days.
Cheers

**Comment by Gui11aum3** [comment]
Hi,
I noticed the same issue when launching a lot of requests. 
It first returned the captcha (geo.captcha-delivery.com), and now a full 403. 
I'll let you know if this gets removed after a few hours/days.

**Comment by clopobec** [comment]
Hi,

I am facing the same issue. It was working perfectly fine the first days and now I get the 403 error. I am located in France. I guess my public IP at home is black listed as it is still fine when I am using the API from my job office. Anyway thank you for sharing this API and hopefully it will again in the future.

Cheers

**Comment by Shinyhero36** [comment]
Hi,

I've never had this problem before. So there's not much I can do about it.
Are you spamming requests with the API? @Gui11aum3 @clopobec 

Cheers

**Comment by clopobec** [comment]
Hi,

It depends on what you mean by spamming. I used the api with a script that was looping on 5 searches/keywords by setting the task scheduler to run every 2 hours. It was ok for 2 days (except the raise of few captcha errors). So let's say 100 requests over 2 days. I was only fetching title, price and url of comics I am interested in. My guess about black listed ip is stupid since I can still access the website using chrome or firefox. My new guess is that datadome is smarter than me :D

Cheers

**Comment by gaetan1903** [comment]
first time to use and get this error 😅

```
 r.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.leboncoin.fr/finder/search

```

**Comment by Shinyhero36** [comment]
Thank you for the issue. I'll try to investigate on this error

**Comment by gaetan1903** [comment]
I've tried in a server where location is France and it works .. wait what? 😅

**Comment by Shinyhero36** [comment]
Yep, kinda strange. Let me know in a couple of days if the issue is solved. @gaetan1903
